version: '3.8'

services:
  web:
    build: .
    container_name: gerenciador-frequencia-web
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    command: python app.py