[tool.semantic_release]
version_variable = [
    "app.py:__version__",  
]
version_toml = [
    "pyproject.toml:tool.poetry.version" 
]
branch = "main"
upload_to_pypi = false
upload_to_release = true
build_command = "echo 'Pula build de pacote python'"
commit_parser = "angular" # Isso espera: feat: ..., fix: ...

[tool.pytest.ini_options]
testpaths = ["tests"]
